---
swagger: "2.0"
info:
  description: "A simple REST API to control a meArm robotic arm."
  version: "1.0.0"
  title: "Avanade meArm REST API"
#host: "192.168.1.253:8080"
basePath: "/Avanade.meArm/1.0.0"
schemes:
- "https"
paths:
  /arm:
    get:
      tags:
      - "Environment"
      description: "Gets the environment tolpology"
      operationId: "get_environment"
      parameters: []
      responses:
        200:
          description: "Successfully retrieved environment topology"
          schema:
            $ref: "#/definitions/Environment"
      x-swagger-router-controller: "server.controllers.environment_controller"
  /arm/{id}:
    get:
      tags:
      - "Status"
      description: "Gets the current status of the meArm."
      operationId: "get_arm"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
        description: "The id of the meArm." 
      responses:
        200:
          description: "Successfully retrieved operational status of the meArm."
          schema:
            $ref: "#/definitions/Status"
      x-swagger-router-controller: "server.controllers.status_controller"
  /arm/{id}/position:
    get:
      tags:
      - "Status"
      description: "Gets hte current position of the meArm"
      operationId: "get_position"
      parameters: 
      - name: "id"
        in: "path"
        required: true
        type: "string"
        description: "The id of the meArm." 
      responses:
        200:
          description: "Successfully obtained position."
          schema:
            $ref: "#/definitions/Point"
      x-swagger-router-controller: "server.controllers.status_controller"
  /arm/{id}/checkout:
    post:
      tags:
      - "Operation"
      description: "Checks out the arm for a session."
      operationId: "checkout"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
        description: "The id of the meArm." 
      responses:
        200:
          description: "Successfully checkout out the meArm"
          schema:
            $ref: "#/definitions/Token"
        403:
          description: "Cannot checkout because arm is checkout to another user."
          schema:
            $ref: "#/definitions/Status"
      x-swagger-router-controller: "server.controllers.operation_controller"
  /arm/{id}/checkin:
    post:
      tags:
      - "Operation"
      description: "Checks in the arm to complete the session and remove the lock"
      operationId: "checkin"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
        description: "The id of the meArm." 
      - name: "token"
        in: "header"
        description: "Session token. This token should be obtained using /arm/checkout."
        required: true
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "Successfully checked in the meArm"
          schema:
            $ref: "#/definitions/SessionStatus"
        403:
          description: "Cannot checkin due to incorrect token. Obtain a token using\
            \ /arm/checkout."
          schema:
            $ref: "#/definitions/Status"
      x-swagger-router-controller: "server.controllers.operation_controller"
  /arm/{id}/operate:
    post:
      tags:
      - "Operation"
      description: "Operates the arm using a list of operations."
      operationId: "operate"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
        description: "The id of the meArm." 
      - name: "token"
        in: "header"
        description: "Session token. This token should be obtained using /arm/checkout."
        required: true
        type: "string"
        format: "uuid"
      - in: "body"
        name: "operations"
        description: "A list of operations to be executed."
        required: true
        schema:
          $ref: "#/definitions/Operations"
      responses:
        200:
          description: "Successfully executed operations."
          schema:
            $ref: "#/definitions/OperationStatus"
        403:
          description: "Cannot operate due to incorrect token. Obtain a token using /arm/checkout."
          schema:
            $ref: "#/definitions/Status"
        413:
          description: "Too many steps. Reduce the number of opertions to 10 or less"
          schema:
            type: "string"
      x-swagger-router-controller: "server.controllers.operation_controller"
definitions:
  Status:
    type: "object"
    properties:
      host:
        type: "string"
      version:
        type: "string"
      checkedOut:
        type: "boolean"
      checkedOutSince:
        type: "string"
        format: "date-time"
      movementsSinceCheckout:
        type: "integer"
        format: "int32"
      position:
        $ref: "#/definitions/Point"
    example:
      checkedOut: true
      movementsSinceCheckout: 0
      host: "host"
      position:
        r: 173.1370849898476
        lng: 90
        x: 0
        y: 173.1370849898476
        z: 0
        lat: 90
      checkedOutSince: "2000-01-23T04:56:07.000+00:00"
      version: "version"
  Point:
    type: "object"
    properties:
      x:
        type: "number"
        format: "double"
      y:
        type: "number"
        format: "double"
      z:
        type: "number"
        format: "double"
      r:
        type: "number"
        format: "double"
      lat:
        type: "number"
        format: "double"
      lng:
        type: "number"
        format: "double"
    example:
        r: 173.1370849898476
        lng: 90
        x: 0
        y: 173.1370849898476
        z: 0
        lat: 90
  Operation:
    type: "object"
    properties:
      type:
        type: "string"
        enum:
        - "moveTo"
        - "grab"
        - "release"
        - "test"
      target:
        $ref: "#/definitions/Point"
  Operations:
    type: "array"
    items:
      $ref: "#/definitions/Operation"
  Environment:
    type: "object"
    properties:
      numberOfControllers:
        type: "number"
        description: "The number of controllers driving meArms."
      numberOfArms:
        type: "number"
        description: "The number of meArms in the environement."
      arms:
        type: "array"
        items:
          type: "string"
    example:
      numberOfControllers: 1
      numberOfArms: 2
      arms: [
        "004902030405",
        "004910111213"
      ]
  Token:
    properties:
      token:
        type: "string"
        format: "uuid"
        example: "0729a580-2240-11e6-9eb5-0002a5d5c51b"
        description: "Token to use for any operation in the session"
    example:
      token: "0729a580-2240-11e6-9eb5-0002a5d5c51b"
  SessionStatus:
    properties:
      checkedOut:
        type: "boolean"
        example: false
      sessionDuration:
        type: "integer"
        format: "int64"
        example: 3996
        description: "The session duration in seconds"
      numberOfOperations:
        type: "integer"
        format: "int32"
        example: 504
        description: "The number of arm movements performed during the session"
    example:
      checkedOut: false
      numberOfOperations: 504
      sessionDuration: 3996
  OperationStatus:
    properties:
      numberOfMovements:
        type: "integer"
        format: "int32"
      duration:
        type: "integer"
        format: "int64"
      position:
        $ref: "#/definitions/Point"
    example:
      duration: 6
      numberOfMovements: 0
      position:
        r: 173.1370849898476
        lng: 90
        x: 0
        y: 173.1370849898476
        z: 0
        lat: 90